### PR TITLE
DDCE-3918 Upgrade maintain-trust-assets-frontend to build jdk 11

### PR DESCRIPTION
**Pull request by gastonracui**

### CODE REVIEW

**Review by ina-tu — COMMENTED** [review]
new warnings about deprecated methods since updating the scala version 
E.g.
- `symbol literal is deprecated; use Symbol("autoComplete") instead` in View files, 
- method right in class Either is deprecated (since 2.13.0): Either is now right-biased, use methods directly on Either

Run `sbt clean compile` to see which files they're in

**Review by ina-tu — CHANGES_REQUESTED** [review]
one of the acceptance tests failed when running `run_local_maintain_assets.sh`

**Comment by ina-tu** [comment]
test this please

**Comment by gastonracui** [comment]
> test this please

sometimes takes a little bit longer

**Comment by ina-tu** [comment]
test this please

**Review by ina-tu — APPROVED** [review]

**Pull request merged**
